test: tst_rast.o raster.o model.o  
	cc68x -g tst_rast.o raster.o model.o -o test  # Link model.o

tst_rast.o: tst_rast.c raster.h types.h bitmaps.h model.h  
	cc68x -g -c tst_rast.c

raster.o: raster.c raster.h
	cc68x -g -c raster.c

model.o: model.c model.h  
	cc68x -g -c model.c  # Compile model.c into model.o

clean:
	$(RM) *.o test