all: clean test

test: aplcatch.o raster.o model.o bitmaps.o events.o renderer.o input.o music.o PSG.o effects.o
	cc68x -g aplcatch.o raster.o model.o bitmaps.o events.o renderer.o input.o music.o PSG.o effects.o -o test  

aplcatch.o: aplcatch.c raster.h types.h bitmaps.h model.h events.h input.h splash.h
	cc68x -g -c aplcatch.c

raster.o: raster.c raster.h splash.h
	cc68x -g -c raster.c

model.o: model.c model.h  
	cc68x -g -c model.c  

bitmaps.o: bitmaps.c bitmaps.h types.h
	cc68x -g -c bitmaps.c  

events.o: events.c events.h
	cc68x -g -c events.c
  
renderer.o: renderer.c renderer.h splash.h
	cc68x -g -c renderer.c

input.o: input.c input.h
	cc68x -g -c input.c 

music.o: music.c music.h PSG.h types.h
	cc68x -g -c music.c

PSG.o: PSG.c PSG.h types.h
	cc68x -g -c PSG.c

effects.o: effects.c effects.h PSG.h types.h
	cc68x -g -c effects.c

clean:
	$(RM) *.o test
