all: clean test

test: aplcatch.o raster.o model.o bitmaps.o events.o renderer.o driver.o input.o
	cc68x -g aplcatch.o raster.o model.o bitmaps.o events.o renderer.o driver.o input.o -o test  

aplcatch.o: aplcatch.c driver.h raster.h types.h bitmaps.h model.h events.h input.h
	cc68x -g -c aplcatch.c

driver.o: driver.c driver.h
	cc68x -g -c driver.c

raster.o: raster.c raster.h
	cc68x -g -c raster.c

model.o: model.c model.h  
	cc68x -g -c model.c  

bitmaps.o: bitmaps.c bitmaps.h types.h
	cc68x -g -c bitmaps.c  

events.o: events.c events.h
	cc68x -g -c events.c
  
renderer.o: renderer.c renderer.h
	cc68x -g -c renderer.c

input.o: input.c input.h
	cc68x -g -c input.c 

clean:
	$(RM) *.o test
