test: stage2.o raster.o bitmaps.o
	cc68x -g stage2.o raster.o bitmaps.o -o test

stage2.o: stage2.c raster.h types.h bitmaps.h
	cc68x -g -c stage2.c

raster.o: raster.c raster.h
	cc68x -g -c raster.c

bitmaps.o: bitmaps.c bitmaps.h
	cc68x -g -c bitmaps.c

clean:
	$(RM) *.o test
