test: stage3.o driver.o raster.o model.o bitmaps.o events.o  
	cc68x -g stage3.o driver.o raster.o model.o bitmaps.o events.o -o test  

stage3.o: stage3.c driver.h raster.h types.h bitmaps.h model.h events.h
	cc68x -g -c stage3.c

driver.o: driver.c driver.h
	cc68x -g -c driver.c

raster.o: raster.c raster.h
	cc68x -g -c raster.c

model.o: model.c model.h  
	cc68x -g -c model.c  

bitmaps.o: bitmaps.c bitmaps.h types.h
	cc68x -g -c bitmaps.c  

events.o: events.c events.h
	cc68x -g -c events.c  

clean:
	$(RM) *.o test    
