test: tst_rast.o raster.o model.o bitmaps.o  
	cc68x -g tst_rast.o raster.o model.o bitmaps.o -o test  

tst_rast.o: tst_rast.c raster.h types.h bitmaps.h model.h  
	cc68x -g -c tst_rast.c

raster.o: raster.c raster.h
	cc68x -g -c raster.c

model.o: model.c model.h  
	cc68x -g -c model.c  

bitmaps.o: bitmaps.c bitmaps.h types.h
	cc68x -g -c bitmaps.c  

clean:
	$(RM) *.o test
