#ifndef TYPES_H
#define TYPES_H
/* 
AUTHORS: John G, Zach L 
FILE NAME: TYPES.H 
PURPOSE: CONTAINS ALL DEFINED DATATYPES AND CONSTANTS
*/
#define SCREEN_HEIGHT 400 
#define SCREEN_WIDTH 640
#define BASKET_HEIGHT 16
#define BASKET_WIDTH 64
#define APPLE_HEIGHT 32
#define APPLE_WIDTH 32
#define CHARACTER_HEIGHT 32
#define NUM_APPLES 5 /* only set to 5 for testing, could be 2 or 3 for final */


typedef unsigned char UINT8;
typedef unsigned int  UINT16;
typedef unsigned long UINT32;

#endif
